repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies: [
          'flake8-builtins==2.0.1',
          'flake8-comprehensions==3.10.1',
          'flake8-django==1.1.5',
          'flake8-eradicate==1.4.0',
          'flake8-print==5.0.0',
          'flake8-simplify==0.19.3',
          'pep8-naming>=0.13.2',
          'flake8-annotations==2.9.1',
      ]