services:
  db:
    image: postgres:14.0
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      file_uploads_net:
    container_name: file_uploads_db
  web: &web
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:${DOCKER_EXPOSE_PORT?8000}:${DJANGO_PORT?8000}"
    depends_on:
      - db
    volumes:
      - ./iconicchain/:/code/iconicchain/
      - ./static/:/code/static/
      - ./media/:/code/media/
      - ./logs:/code/logs/
    restart: unless-stopped
    networks:
      file_uploads_net:
    command: /start
    container_name: file_uploads_web

networks:
  file_uploads_net: